<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Submission_infos extends Model
{
    public $timestamps = true;
    protected $fillable = [
        'id',
        'institute_id',
        'com_1st_page',
        'com_2nd_page',
        'com_3rd_page',
        'com_4th_page',
        'com_5th_page',
        'com_tech_staf_page',
        'school_1st_page',
        'school_2nd_page',
        'school_3rd_page',
        'school_4th_page',
        'school_5th_page',
        'school_col_1st_page',
        'school_col_2nd_page',
        'school_col_3rd_page',
        'school_col_4th_page',
        'school_col_5th_page',
        'school_col_6th_page',
        'college_1st_page',
        'college_2nd_page',
        'college_3rd_page',
        'college_4th_page',
        'college_5th_page',
        'madrasa_1st_page',
        'madrasa_2nd_page',
        'madrasa_3rd_page',
        'madrasa_4th_page',
        'madrasa_5th_page',
        'madrasa_6th_page',
        'madrasa_7th_page',
        'tec_1st_page',
        'tec_2nd_page',
        'tec_3rd_page',
        'tec_4th_page',
        'tec_5th_page',
        'tec_6th_page',
        'tec_7th_page',
        'tec_8th_page',
        'pub_uni_1st_page',
        'pub_uni_2nd_page',
        'pub_uni_3rd_page',
        'pub_uni_4th_page',
        'pub_uni_5th_page',
        'pub_uni_6th_page',
        'prv_uni_1st_page',
        'prv_uni_2nd_page',
        'prv_uni_3rd_page',
        'prv_uni_4th_page',
        'prv_uni_5th_page',
        'prv_uni_6th_page',
        'prof_1st_page',
        'prof_2nd_page',
        'prof_3rd_page',
        'prof_4th_page',
        'ttc_1st_page',
        'ttc_2nd_page',
        'medical_1st_page',
        'medical_2nd_page',
        'english_1st_page',
        'english_2nd_page',
        'english_3rd_page',
        'year',
        'created_at',
        'updated_at',
    ];
}
